services:
  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    restart: unless-stopped

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack_server
    ports:
      # Maps the Redis Stack server port to 16379 on the host to avoid conflicts with the other Redis instance.
      # You can connect to this Redis instance at redis://localhost:16379
      - "16379:6379"
      - "8001:8001" # RedisInsight UI
    restart: unless-stopped
